name: TestLibrary
options:
  bundleIdPrefix: com.test
  deploymentTarget:
    iOS: 13.0
  createIntermediateGroups: true

settings:
  MARKETING_VERSION: 1.0.0
  CURRENT_PROJECT_VERSION: 1
  GENERATE_INFOPLIST_FILE: YES
  BUILD_LIBRARY_FOR_DISTRIBUTION: YES
  SKIP_INSTALL: NO

targets:
  TestLibrary:
    type: framework
    platform: iOS
    sources:
      - path: Sources/TestLibrary
    settings:
      PRODUCT_NAME: TestLibrary
      PRODUCT_BUNDLE_IDENTIFIER: com.test.TestLibrary
      MACH_O_TYPE: mh_dylib
      DEFINES_MODULE: YES
      BUILD_LIBRARY_FOR_DISTRIBUTION: YES
      SKIP_INSTALL: NO
      INSTALL_PATH: "@rpath"
      LD_RUNPATH_SEARCH_PATHS:
        - "$(inherited)"
        - "@executable_path/Frameworks"
        - "@loader_path/Frameworks"
      SWIFT_VERSION: 5.0
      ENABLE_MODULE_VERIFIER: YES
      MODULE_VERIFIER_SUPPORTED_LANGUAGE_STANDARDS: "gnu11 gnu++20"

schemes:
  TestLibrary:
    build:
      targets:
        TestLibrary: all
    archive:
      config: Release